steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'us-central1-docker.pkg.dev/mnist-cnn-447812/repository/mnist-cnn-image',
    '-f',
    'dockerfiles/api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'us-central1-docker.pkg.dev/mnist-cnn-447812/repository/mnist-cnn-image'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'mnist-cnn-api',
    '--image',
    'us-central1-docker.pkg.dev/mnist-cnn-447812/repository/mnist-cnn-image',
    '--region',
    'us-central1',
    '--platform',
    'managed',
  ]
options:
  logging: CLOUD_LOGGING_ONLY